import * as fc from 'fast-check';
import { nlpService } from '../nlpService';

/**
 * Feature: nlp-enhanced-search, Property 4: Fallback to keyword search
 * Validates: Requirements 1.4
 * 
 * For any query where no valid filters can be extracted,
 * the system should perform a standard keyword search using the original query text
 */
describe('Property 4: Fallback to keyword search', () => {
  const skipIfNotConfigured = () => {
    if (!nlpService.isReady()) {
      console.warn('Skipping NLP tests: GEMINI_API_KEY not configured');
      return true;
    }
    return false;
  };


});

/**
 * Feature: nlp-enhanced-search, Property 11: Sensitive data not logged
 * Validates: Requirements 6.4
 * 
 * For any error or log message generated by the NLP service,
 * the log output should not contain the API key or other sensitive credentials
 */
describe('Property 11: Sensitive data not logged', () => {
  it('should sanitize API keys from error messages', () => {
    const testError = {
      message: 'Error with API key AIzaSyAbc123def456ghi789jkl012mno345pqr'
    };

    // Access private method through any type
    const sanitized = (nlpService as any).sanitizeError(testError);

    // API key should be redacted
    expect(sanitized.message).not.toContain('AIzaSy');
    expect(sanitized.message).toContain('[REDACTED]');
  });

  it('should handle errors without exposing sensitive data in logs', () => {
    // Test that the sanitizeError method works correctly
    const testError = {
      message: 'Failed to connect to API with key AIzaSyAbc123def456ghi789jkl012mno345pqr',
      stack: 'Error: API key AIzaSyXyz987wvu654tsr321qpo098nml765kji was invalid'
    };

    const sanitized = (nlpService as any).sanitizeError(testError);

    // Both API keys should be redacted
    expect(sanitized.message).not.toContain('AIzaSyAbc123');
    expect(sanitized.message).not.toContain('AIzaSyXyz987');
    expect(sanitized.message).toContain('[REDACTED]');
  });
});